import {kronosForecast} from '../../infrastructure/models/kronosForecast.js';

function clamp(n,min=0,max=1){return Math.max(min,Math.min(max,n));}
function sma(a,n){if(a.length<n)return null;return a.slice(-n).reduce((x,y)=>x+y,0)/n;}
function pct(a,b){return b?((a/b)-1)*100:0;}
export class MomentumScanner{
  constructor({marketData,bus,onStatus,onScan}){
    this.marketData=marketData;this.bus=bus;this.onStatus=onStatus;this.onScan=onScan;this.running=false;
    this.symbols=String(process.env.MOM_SYMBOLS||'BTCUSDT,ETHUSDT,SOLUSDT').split(',').map(s=>s.trim().toUpperCase()).filter(Boolean);
    this.interval=process.env.MOM_INTERVAL||'5m';this.lookback=Math.max(80,Number(process.env.MOM_LOOKBACK||180));this.scanEveryMs=Math.max(10000,Number(process.env.MOM_SCAN_MS||30000));
    this.fast=Math.max(5,Number(process.env.MOM_FAST_SMA||12));this.slow=Math.max(this.fast+5,Number(process.env.MOM_SLOW_SMA||36));this.minTrendPct=Math.max(.05,Number(process.env.MOM_MIN_TREND_PCT||.25));
  }
  config(){return {provider:'Binance Spot public market data',symbols:this.symbols,interval:this.interval,lookback:this.lookback,fastSma:this.fast,slowSma:this.slow,minTrendPct:this.minTrendPct,scanEveryMs:this.scanEveryMs,configured:!!this.symbols.length};}
  analyze(symbol,k){const c=k.slice(0,-1);if(c.length<this.slow+5)throw new Error('NOT_ENOUGH_KLINES');const closes=c.map(x=>x.close),fast=sma(closes,this.fast),slow=sma(closes,this.slow),last=closes.at(-1),prevSlow=sma(closes.slice(0,-3),this.slow);const trendPct=pct(fast,slow),slopePct=pct(slow,prevSlow),ret1h=pct(last,closes.at(-13)||closes[0]);const direction=trendPct>=0&&slopePct>=0?'LONG':trendPct<=0&&slopePct<=0?'SHORT':'NEUTRAL';const strength=clamp(Math.abs(trendPct)/1.5*.45+Math.abs(slopePct)/.8*.25+Math.abs(ret1h)/3*.3);const triggered=direction!=='NEUTRAL'&&Math.abs(trendPct)>=this.minTrendPct&&strength>=.45;return {symbol,price:last,fastSma:Number(fast.toFixed(4)),slowSma:Number(slow.toFixed(4)),trendPct:Number(trendPct.toFixed(4)),slopePct:Number(slopePct.toFixed(4)),return1hPct:Number(ret1h.toFixed(4)),direction,strength:Number(strength.toFixed(3)),triggered,scannedAt:new Date().toISOString()};}
  async scanOnce(){if(this.running)return;this.running=true;this.onStatus?.('SCANNING_REAL');try{for(const symbol of this.symbols){try{const k=await this.marketData.klines(symbol,this.interval,this.lookback);const baseScan=this.analyze(symbol,k);const kronos=await kronosForecast({symbol,interval:this.interval,candles:k,predLen:Math.min(12,Math.max(4,Math.floor(this.lookback/10)))});const scan={...baseScan,kronos:kronos?.available?{summary:kronos.summary,model:kronos.model,generatedAt:kronos.generatedAt}:null};this.onScan?.(scan);if(!scan.triggered)continue;const agreement=!kronos?.available||kronos.summary?.direction===scan.direction;const notional=Math.max(100,Number(process.env.MOM_PAPER_NOTIONAL_USD||1500));const confidence=clamp(.64+scan.strength*.3+(kronos?.available?(agreement ? .04 : -.06):0));this.bus.emit('raw-opportunity',{strategyId:'momentum',strategy:'Momentum / Trend Agent',network:'Binance Spot',asset:symbol,confidence,executionProbability:clamp(.62+scan.strength*.28),expectedProfitUsd:Number((notional*Math.min(.025,Math.abs(scan.return1hPct)/100)*(.3+.5*scan.strength)).toFixed(2)),capitalRequiredUsd:notional,estimatedSlippageBps:12,riskScore:clamp(.52-scan.strength*.2+(kronos?.available && !agreement ? .08 : 0)),source:'BINANCE_SPOT_MOMENTUM_REAL',synthetic:false,expiresAt:new Date(Date.now()+this.scanEveryMs*2).toISOString(),metadata:{...scan,kronosAgreement:kronos?.available?agreement:null,signalModel:'SMA_TREND_SLOPE_PLUS_KRONOS',executionModel:'PAPER_ONLY'}});}catch(error){this.onScan?.({symbol,error:error?.message||'MOMENTUM_SCAN_ERROR',scannedAt:new Date().toISOString()});}}}catch{this.onStatus?.('SCAN_ERROR');}finally{this.running=false;}}
  start(){this.scanOnce();this.timer=setInterval(()=>this.scanOnce(),this.scanEveryMs);return()=>clearInterval(this.timer);}
}
