import {randomUUID} from 'node:crypto';
import {isAddress} from 'ethers';

const safe=v=>{if(typeof v==='bigint')return v.toString();if(Array.isArray(v))return v.map(safe);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,safe(x)]));return v;};
const DOMAIN_FIELDS=[{name:'name',type:'string'},{name:'version',type:'string'},{name:'chainId',type:'uint256'},{name:'verifyingContract',type:'address'}];
const LABELS={ClobAuth:'Autenticación Polymarket (no mueve fondos)',Order:'Orden Polymarket (operación específica)',TypedDataSign:'Firma Polymarket'};

class BridgeSigner {
  constructor(timeoutMs){this.address=null;this.pending=new Map();this.waiters=new Map();this.timeoutMs=timeoutMs;}
  connect(address){this.address=address.toLowerCase();}
  disconnect(){for(const w of this.waiters.values()){clearTimeout(w.timer);w.reject(new Error('wallet disconnected'));}this.waiters.clear();this.pending.clear();this.address=null;}
  async getAddress(){if(!this.address)throw new Error('POLYMARKET_WALLET_NOT_CONNECTED');return this.address;}
  async _signTypedData(domain,types,message){if(!this.address)throw new Error('POLYMARKET_WALLET_NOT_CONNECTED');const id=randomUUID();const primaryType=Object.keys(types)[0]||'Order';const request={id,label:LABELS[primaryType]||'Firma solicitada por Polymarket',primaryType,domain:safe(domain),types:{EIP712Domain:DOMAIN_FIELDS,...types},message:safe(message),createdAt:new Date().toISOString()};this.pending.set(id,request);return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.pending.delete(id);this.waiters.delete(id);reject(new Error('POLYMARKET_SIGNATURE_TIMEOUT'));},this.timeoutMs);this.waiters.set(id,{resolve,reject,timer});});}
  listPending(){return [...this.pending.values()];}
  resolve(id,signature){const w=this.waiters.get(id);if(!w)return false;clearTimeout(w.timer);this.waiters.delete(id);this.pending.delete(id);w.resolve(signature);return true;}
  reject(id,reason='rejected by user'){const w=this.waiters.get(id);if(!w)return false;clearTimeout(w.timer);this.waiters.delete(id);this.pending.delete(id);w.reject(new Error(reason));return true;}
}

export class PolymarketTradingConnector {
  constructor({data}){this.data=data;this.gamma=process.env.POLYMARKET_GAMMA_URL||'https://gamma-api.polymarket.com';this.clob=process.env.POLYMARKET_CLOB_URL||'https://clob.polymarket.com';this.enabled=String(process.env.POLYMARKET_LIVE_ENABLED||'false').toLowerCase()==='true';this.chainId=Number(process.env.POLYMARKET_LIVE_CHAIN_ID||137);this.positionSize=Number(process.env.POLYMARKET_LIVE_POSITION_SIZE||5);this.maxOpen=Number(process.env.POLYMARKET_LIVE_MAX_OPEN_POSITIONS||5);this.maxExposure=Number(process.env.POLYMARKET_LIVE_MAX_TOTAL_EXPOSURE||50);this.timeoutMs=Number(process.env.POLYMARKET_LIVE_SIGNATURE_TIMEOUT_MS||120000);this.signer=new BridgeSigner(this.timeoutMs);this.client=null;this.authClient=null;this.creds=null;this.proposals=[];}
  status(){return{provider:'Polymarket CLOB',enabled:this.enabled,chainId:this.chainId,address:this.signer.address,connected:Boolean(this.signer.address),authenticated:Boolean(this.creds),pendingSignatures:this.signer.listPending().length,proposals:this.proposals.length,positionSize:this.positionSize,maxOpenPositions:this.maxOpen,maxTotalExposure:this.maxExposure,privateKeyStoredInApp:false};}
  async connect(address){if(!isAddress(address))throw new Error('POLYMARKET_INVALID_WALLET');if(!this.enabled)throw new Error('POLYMARKET_LIVE_TRADING_LOCKED');this.signer.connect(address);try{const {ClobClient}=await import('@polymarket/clob-client-v2');this.client=new ClobClient({host:this.clob,chain:this.chainId,signer:this.signer});this.creds=await this.client.createOrDeriveApiKey();this.authClient=new ClobClient({host:this.clob,chain:this.chainId,signer:this.signer,creds:this.creds});return this.status();}catch(error){this.signer.disconnect();this.client=null;this.authClient=null;this.creds=null;throw error;}}
  disconnect(){this.signer.disconnect();this.client=null;this.authClient=null;this.creds=null;}
  pendingSignatures(){return this.signer.listPending();}
  resolveSignature(id,signature){return signature?this.signer.resolve(id,signature):this.signer.reject(id,'rejected by user');}
  async balance(){if(!this.authClient)throw new Error('POLYMARKET_WALLET_NOT_CONNECTED');const {AssetType}=await import('@polymarket/clob-client-v2');return this.authClient.getBalanceAllowance({asset_type:AssetType.COLLATERAL});}
  maybePropose(opportunity){if(!this.enabled||!this.authClient||opportunity.strategyId!=='polymarket'||opportunity.metadata?.direction==='WATCH_DISLOCATION')return null;if(this.proposals.filter(p=>['pending','building','submitted'].includes(p.status)).length>=this.maxOpen)return null;if(this.proposals.filter(p=>['pending','building','submitted'].includes(p.status)).reduce((a,p)=>a+p.size,0)+this.positionSize>this.maxExposure)return null;const tokenId=String(opportunity.metadata?.yesTokenId||'');if(!tokenId)return null;const p={id:randomUUID(),opportunityId:opportunity.id,marketId:String(opportunity.metadata?.marketId||opportunity.asset||''),question:opportunity.metadata?.question||'',tokenId,side:'BUY',price:Number(opportunity.metadata?.mid||0),size:this.positionSize,status:'pending',createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+Number(process.env.POLYMARKET_LIVE_PROPOSAL_TTL_MS||300000)).toISOString()};this.proposals.unshift(p);this.proposals=this.proposals.slice(0,200);return p;}
  listProposals(){for(const p of this.proposals)if(p.status==='pending'&&Date.now()>Date.parse(p.expiresAt))p.status='expired';return this.proposals;}
  rejectProposal(id){const p=this.proposals.find(x=>x.id===id);if(p&&p.status==='pending'){p.status='rejected';p.resolvedAt=new Date().toISOString();}return p;}
  async approveProposal(id){const p=this.proposals.find(x=>x.id===id);if(!p)throw new Error('POLYMARKET_PROPOSAL_NOT_FOUND');if(p.status!=='pending')throw new Error(`POLYMARKET_PROPOSAL_${p.status.toUpperCase()}`);if(Date.now()>Date.parse(p.expiresAt)){p.status='expired';throw new Error('POLYMARKET_PROPOSAL_EXPIRED');}if(!this.authClient)throw new Error('POLYMARKET_WALLET_NOT_CONNECTED');p.status='building';try{const {OrderType,Side}=await import('@polymarket/clob-client-v2');const response=await this.authClient.createAndPostMarketOrder({tokenID:p.tokenId,side:Side.BUY,amount:p.size},{},OrderType.FOK);p.status='submitted';p.orderResponse=response;p.resolvedAt=new Date().toISOString();return p;}catch(error){p.status='failed';p.error=error?.message||String(error);p.resolvedAt=new Date().toISOString();throw error;}}
}
