import PDFDocument from "pdfkit";

const INK = "#0a1122";
const MUTED = "#5c6884";
const ACCENT = "#0e7490";
const GREEN = "#0f7a4f";
const RED = "#b3273e";
const RULE = "#d8dee8";

function money(value) {
  return `$${Math.round(Number(value) || 0).toLocaleString("en-US")}`;
}

function ensureSpace(doc, needed) {
  if (doc.y + needed > doc.page.height - doc.page.margins.bottom) doc.addPage();
}

function sectionHeader(doc, title) {
  ensureSpace(doc, 60);
  doc.moveDown(0.8);
  doc.fontSize(13).fillColor(INK).font("Helvetica-Bold").text(title.toUpperCase());
  doc.moveTo(doc.x, doc.y + 2).lineTo(doc.page.width - doc.page.margins.right, doc.y + 2).strokeColor(RULE).lineWidth(1).stroke();
  doc.moveDown(0.6);
  doc.font("Helvetica").fillColor(INK);
}

// Uses pdfkit's own line-flow ({continued: true} keeps writing on the same line) instead of
// manually positioned x/y columns — an earlier version positioned label and value independently
// and they drifted apart because a plain `.text()` call also moves pdfkit's internal cursor even
// when you pass explicit coordinates, so a second call computed its offset from a cursor that had
// already moved. Letting pdfkit own the cursor end to end avoids that class of bug entirely.
function kv(doc, label, value) {
  ensureSpace(doc, 16);
  doc.fontSize(9).fillColor(MUTED).font("Helvetica").text(`${label}:  `, {continued: true});
  doc.fontSize(10).fillColor(INK).font("Helvetica-Bold").text(String(value));
  doc.moveDown(0.2);
}

function gateRow(doc, gate) {
  ensureSpace(doc, 32);
  doc.fontSize(9.5).font("Helvetica-Bold").fillColor(gate.passed ? GREEN : RED).text(`${gate.passed ? "PASA" : "BLOQUEA"}  `, {continued: true});
  doc.fillColor(INK).text(gate.label);
  doc.fontSize(8.5).font("Helvetica").fillColor(MUTED).text(gate.detail);
  doc.moveDown(0.35);
}

function agentTurn(doc, entry) {
  ensureSpace(doc, 45);
  doc.fontSize(9.5).font("Helvetica-Bold").fillColor(INK).text(`${entry.alias}${entry.reference ? ` (${entry.reference})` : ""}  `, {continued: true});
  const decisionColor = ["APPROVE", "APPROVE_WITH_CONDITIONS"].includes(entry.decision) ? GREEN : RED;
  doc.fillColor(decisionColor).text(entry.decision);
  doc.fontSize(9).font("Helvetica").fillColor(INK).text(entry.team_message || "");
  doc.moveDown(0.4);
}

// pdfkit auto-inserts a new page as soon as flowing text would cross the bottom margin, so
// drawing a footer *inside* that margin band (where it belongs) has to temporarily widen the
// page by zeroing the margin for the duration of the footer draw, or every footer silently
// spawns a blank trailing page instead of annotating the page it's meant for.
function footer(doc, pageLabel) {
  const originalBottom = doc.page.margins.bottom;
  doc.page.margins.bottom = 0;
  const y = doc.page.height - 40;
  doc.fontSize(7.5).fillColor(MUTED).font("Helvetica")
    .text("Institutional Brain · reporte generado automáticamente por simulación institucional (IA real, agentes de rol simulados) — no constituye asesoría financiera, legal o de inversión real.", doc.page.margins.left, y, {width: doc.page.width - doc.page.margins.left - doc.page.margins.right - 70});
  doc.text(pageLabel, doc.page.width - doc.page.margins.right - 60, y, {width: 60, align: "right"});
  doc.page.margins.bottom = originalBottom;
}

// Renders the report data from dealReport.js into a professional PDF, returned as a Buffer.
// pdfkit draws directly (no headless browser dependency), which keeps this cheap to run on a
// real server — every number on the page traces back to a deterministic engine already used
// elsewhere in the app; nothing here is generated by an LLM.
export function renderDealReportPdf(report) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({size: "A4", margin: 50, bufferPages: true});
    const buffers = [];
    doc.on("data", chunk => buffers.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(buffers)));
    doc.on("error", reject);

    // Cover
    doc.fontSize(9).fillColor(ACCENT).font("Helvetica-Bold").text("INSTITUTIONAL BRAIN");
    doc.fontSize(22).fillColor(INK).font("Helvetica-Bold").text(report.deal.name, {width: 480});
    doc.fontSize(11).fillColor(MUTED).font("Helvetica").text(`${report.deal.dealType} · ${report.deal.assetName}`);
    doc.moveDown(0.3);
    doc.fontSize(8.5).fillColor(MUTED).text(`Generado ${new Date(report.generatedAt).toLocaleString("es-ES")} · Deal ID ${report.deal.id}`);
    doc.moveDown(1);

    sectionHeader(doc, "Resumen del deal");
    kv(doc, "Estado", report.deal.status);
    kv(doc, "Vehículo", report.deal.vehicle);
    kv(doc, "Valor del activo", money(report.deal.assetValueUsd));
    kv(doc, "Inversionistas", `${report.deal.investorsCount} (${report.deal.eligibility})`);
    kv(doc, "Lock-up", `${report.deal.lockupMonths} meses`);
    kv(doc, "Jurisdicciones", report.deal.jurisdictions.join(", "));
    kv(doc, "Distribución", report.deal.distributionFrequency);
    kv(doc, "Capital senior / junior", `${money(report.deal.seniorCapitalUsd)} / ${money(report.deal.juniorCapitalUsd)}`);
    kv(doc, "Cash flow anual", money(report.deal.annualCashflowUsd));

    sectionHeader(doc, "Scores deterministas");
    kv(doc, "Security score", `${report.scores.security.score}/100`);
    kv(doc, "Compliance score", `${report.scores.compliance.score}/100`);
    kv(doc, "Risk score (overall)", `${report.scores.risk.overall}/100`);

    if (report.simulation) {
      sectionHeader(doc, "Simulación financiera");
      const failing = report.simulation.invariants.filter(item => !item.satisfied);
      kv(doc, "Invariantes", failing.length ? `${failing.length} violado(s)` : "Los 7 pasan");
      if (report.simulation.totals) {
        Object.entries(report.simulation.totals).slice(0, 6).forEach(([key, value]) => {
          kv(doc, key, typeof value === "number" ? money(value) : String(value));
        });
      }
    }

    sectionHeader(doc, "Approval gates de producción");
    doc.fontSize(9).fillColor(INK).text(report.approvalGates.recommendation, {width: 480});
    doc.moveDown(0.4);
    report.approvalGates.gates.forEach(gate => gateRow(doc, gate));

    sectionHeader(doc, "Gobernanza · sign-off por etapa");
    report.governance.forEach(stage => {
      ensureSpace(doc, 16);
      const color = stage.decision === "APPROVED" ? GREEN : stage.decision === "REJECTED" ? RED : MUTED;
      doc.fontSize(9.5).font("Helvetica-Bold").fillColor(INK).text(`${stage.stage}:  `, {continued: true});
      doc.fillColor(color).text(stage.decision);
    });

    sectionHeader(doc, "Decisión de tokenización (NEXUS)");
    doc.fontSize(11).font("Helvetica-Bold").fillColor(ACCENT).text(report.tokenizationFit.output);
    doc.fontSize(9).font("Helvetica").fillColor(INK).moveDown(0.2).text(report.tokenizationFit.reasoning, {width: 480});
    doc.moveDown(0.4);
    report.tokenizationFit.answers.forEach(answer => {
      ensureSpace(doc, 14);
      doc.fontSize(8.5).fillColor(answer.yes ? GREEN : MUTED).font("Helvetica-Bold").text(`${answer.yes ? "SÍ" : "NO"}  `, {continued: true});
      doc.font("Helvetica").fillColor(INK).text(answer.text);
    });

    if (report.nexusSessions.length) {
      sectionHeader(doc, "Sesiones NEXUS recientes");
      report.nexusSessions.forEach(session => {
        ensureSpace(doc, 40);
        doc.fontSize(10.5).font("Helvetica-Bold").fillColor(INK).text(`#${session.scenarioNumber} · ${session.title}`, {width: 480});
        doc.fontSize(8).font("Helvetica").fillColor(MUTED).text(`${session.category} · ${new Date(session.completedAt).toLocaleString("es-ES")}`);
        doc.moveDown(0.3);
        session.transcript.forEach(entry => agentTurn(doc, entry));
        if (session.synthesis?.agreements?.length) {
          doc.fontSize(9).font("Helvetica-Bold").fillColor(GREEN).text(session.synthesis.agreements.join(" "));
        } else if (session.synthesis?.disagreements?.length) {
          doc.fontSize(8.5).font("Helvetica").fillColor(RED).text("Sin consenso unánime.");
        }
        doc.moveDown(0.6);
      });
    }

    const pageCount = doc.bufferedPageRange().count;
    for (let index = 0; index < pageCount; index += 1) {
      doc.switchToPage(index);
      footer(doc, `Página ${index + 1} de ${pageCount}`);
    }

    doc.end();
  });
}
