const num=x=>Number.isFinite(Number(x))?Number(x):0;
const best=(levels,side)=>{const vals=(levels||[]).map(x=>num(x.price)).filter(Number.isFinite);if(!vals.length)return null;return side==='bid'?Math.max(...vals):Math.min(...vals);};
export class PolymarketScanner{
  constructor({data,bus,onStatus,onScan}){this.data=data;this.bus=bus;this.onStatus=onStatus;this.onScan=onScan;this.timer=null;}
  config(){return{configured:true,readOnly:true,limit:Number(process.env.POLYMARKET_MARKET_LIMIT||20),scanEveryMs:Number(process.env.POLYMARKET_SCAN_MS||30000),maxSpreadBps:Number(process.env.POLYMARKET_MAX_SPREAD_BPS||500),minLiquidityUsd:Number(process.env.POLYMARKET_MIN_LIQUIDITY_USD||10000),minVolume24hUsd:Number(process.env.POLYMARKET_MIN_VOLUME_24H_USD||25000)};}
  start(){const ms=this.config().scanEveryMs;setTimeout(()=>this.scanOnce().catch(()=>{}),2500);this.timer=setInterval(()=>this.scanOnce().catch(()=>{}),Math.max(15000,ms));}
  async scanOnce(){const cfg=this.config();this.onStatus?.('SCANNING');const at=new Date().toISOString();try{const markets=await this.data.activeMarkets(cfg.limit);const rows=[];for(const m of markets){const token=m.clobTokenIds?.[0];if(!token)continue;let book;try{book=await this.data.book(token);}catch{continue;}const bid=best(book.bids,'bid'),ask=best(book.asks,'ask');if(bid==null||ask==null)continue;const mid=(bid+ask)/2,spread=Math.max(0,ask-bid),spreadBps=mid?spread/mid*10000:0,volume=num(m.volume24hr??m.volume24h??m.volume),liquidity=num(m.liquidityNum??m.liquidity),gammaYes=num(m.outcomePrices?.[0]),dislocationBps=gammaYes&&mid?Math.abs(mid-gammaYes)/mid*10000:0,confidence=Math.min(.96,.58+Math.min(.2,volume/1000000)+Math.min(.12,liquidity/2000000)+Math.min(.06,dislocationBps/2500)),triggered=volume>=cfg.minVolume24hUsd&&liquidity>=cfg.minLiquidityUsd&&spreadBps<=cfg.maxSpreadBps&&dislocationBps>=Number(process.env.POLYMARKET_MIN_DISLOCATION_BPS||75);const direction=mid<gammaYes?'LONG':'SHORT',row={marketId:m.id,question:m.question,slug:m.slug,bid:+bid.toFixed(4),ask:+ask.toFixed(4),mid:+mid.toFixed(4),gammaYes:+gammaYes.toFixed(4),spreadBps:+spreadBps.toFixed(1),dislocationBps:+dislocationBps.toFixed(1),volume24hUsd:+volume.toFixed(2),liquidityUsd:+liquidity.toFixed(2),confidence:+confidence.toFixed(3),direction,triggered};rows.push(row);if(triggered){this.bus.emit('raw-opportunity',{strategyId:'polymarket',strategy:'Polymarket Intelligence',network:'Polygon',asset:`POLY:${m.id}`,direction,confidence,executionProbability:.88,expectedProfitUsd:Number(Math.max(5,Math.min(250,dislocationBps/10)).toFixed(2)),capitalRequiredUsd:Number(process.env.POLYMARKET_PAPER_NOTIONAL_USD||500),estimatedSlippageBps:spreadBps/2,riskScore:Math.min(.7,spreadBps/1000),source:'POLYMARKET_GAMMA_CLOB_REAL',synthetic:false,expiresAt:new Date(Date.now()+cfg.scanEveryMs*1.5).toISOString(),metadata:{marketId:m.id,direction,outcome:'YES',question:m.question,slug:m.slug,yesTokenId:token,bid,ask,mid,gammaYes,volume24hUsd:volume,liquidityUsd:liquidity,dislocationBps}});}}
    const scan={scannedAt:at,provider:'Polymarket Gamma + CLOB',marketCount:rows.length,triggers:rows.filter(x=>x.triggered).length,markets:rows.slice(0,30)};this.onScan?.(scan);this.onStatus?.('SCANNING');return scan;}catch(e){const scan={scannedAt:at,error:e?.message||'POLYMARKET_SCAN_ERROR'};this.onScan?.(scan);this.onStatus?.('ERROR');return scan;}}
}
