// Renders Daml SOURCE TEXT from a Financial Contract Specification. Code generation only —
// nothing here invokes `daml build` or deploys to a Canton participant node.
function header(name, spec) {
  return `-- Generated by Institutional Brain — Financial Specification Engine\n` +
    `-- Deal: ${spec.name} (${spec.dealType})\n` +
    `module ${name} where\n\n`;
}

const GENERATORS = {
  "investor-registry": (spec) => header("InvestorRegistry", spec) +
`template InvestorRegistry
  with
    operator : Party
    investor : Party
    eligibility : Text -- "${spec.investors.eligibility}"
    kycPassed : Bool
  where
    signatory operator
    observer investor

    choice Approve : ContractId InvestorRegistry
      controller operator
      do
        assertMsg "KYC_REQUIRED" kycPassed
        create this
`,
  "spv-ownership": (spec) => header(`${spec.vehicle}Ownership`, spec) +
`template ${spec.vehicle}Ownership
  with
    operator : Party
    investor : Party
    units : Int
    authorizedUnits : Int -- ${spec.investors.count}
  where
    signatory operator
    observer investor

    choice IssueUnits : ContractId ${spec.vehicle}Ownership
      with newUnits : Int
      controller operator
      do
        assertMsg "EXCEEDS_AUTHORIZED_UNITS" (units + newUnits <= authorizedUnits)
        create this with units = units + newUnits
`,
  "compliance-transfer-controller": (spec) => header("ComplianceTransferController", spec) +
`template ComplianceTransferController
  with
    operator : Party
    lockupMonths : Int -- ${spec.lockupMonths}
    whitelistOnly : Bool -- ${spec.compliance.whitelistOnly}
  where
    signatory operator

    nonconsuming choice CanTransfer : Bool
      with toWhitelisted : Bool, monthsHeld : Int
      controller operator
      do
        pure (not whitelistOnly || toWhitelisted) && monthsHeld >= lockupMonths
`,
  "distribution-contract": (spec) => header("DistributionContract", spec) +
`template DistributionContract
  with
    operator : Party
    frequency : Text -- "${spec.distribution.frequency}"
    managementFeeBps : Int -- ${Math.round(spec.finance.feePct * 100)}
  where
    signatory operator

    nonconsuming choice Distribute : Decimal
      with availableCash : Decimal, requestedCash : Decimal
      controller operator
      do
        assertMsg "DISTRIBUTION_EXCEEDS_AVAILABLE_CASH" (requestedCash <= availableCash)
        pure requestedCash
`,
  "escrow-contract": (spec) => header("EscrowContract", spec) +
`template EscrowContract
  with
    operator : Party
    reserveTarget : Decimal -- ${spec.finance.reserveTargetUsd}
    reserveBalance : Decimal
  where
    signatory operator

    choice FundReserve : ContractId EscrowContract
      with amount : Decimal
      controller operator
      do create this with reserveBalance = reserveBalance + amount
`,
  "treasury-controller": (spec) => header("TreasuryController", spec) +
`template TreasuryController
  with
    operator : Party
    signers : [Party] -- ${spec.custody.multisigSigners} configured signers
    threshold : Int -- ${spec.custody.multisigThreshold}
  where
    signatory signers

    choice Withdraw : Bool
      with approvals : Int
      controller operator
      do
        assertMsg "MULTISIG_THRESHOLD_NOT_MET" (approvals >= threshold)
        pure True
`,
  "debt-contract": (spec) => header("DebtContract", spec) +
`template DebtContract
  with
    operator : Party
    principalUsd : Decimal -- ${spec.finance.seniorCapitalUsd}
    ratePct : Decimal -- ${spec.finance.ratePct}
  where
    signatory operator

    nonconsuming choice AccrueInterest : Decimal
      with outstanding : Decimal
      controller operator
      do pure (outstanding * ratePct / 100.0 / 12.0)
`,
  "waterfall-contract": (spec) => header("WaterfallContract", spec) +
`template WaterfallContract
  with
    operator : Party
    trancheCount : Int -- ${(spec.tranches || []).length}
  where
    signatory operator

    nonconsuming choice PayInPriorityOrder : Decimal
      with trancheAmount : Decimal, available : Decimal
      controller operator
      do pure (min trancheAmount available)
`,
  "redemption-contract": (spec) => header("RedemptionContract", spec) +
`template RedemptionContract
  with
    operator : Party
    lockupMonths : Int -- ${spec.lockupMonths}
    noticeMonths : Int -- ${spec.redemptionNoticeMonths || 0}
  where
    signatory operator

    nonconsuming choice CanRedeem : Bool
      with monthsHeld : Int, noticeGivenMonths : Int
      controller operator
      do pure (monthsHeld >= lockupMonths && noticeGivenMonths >= noticeMonths)
`,
  "governance-contract": (spec) => header("GovernanceContract", spec) +
`template GovernanceContract
  with
    operator : Party
    stage : Text
    approved : Bool
  where
    signatory operator

    choice ApproveStage : ContractId GovernanceContract
      controller operator
      do create this with approved = True
`,
  "emergency-controls": (spec) => header("EmergencyControls", spec) +
`template EmergencyControls
  with
    guardian : Party -- "${spec.transfer.approver}"
    paused : Bool
  where
    signatory guardian

    choice Pause : ContractId EmergencyControls
      controller guardian
      do create this with paused = True

    choice Unpause : ContractId EmergencyControls
      controller guardian
      do create this with paused = False
`
};

export function generateCantonSource(spec, architecture) {
  return architecture.map(contract => ({
    id: contract.id,
    name: contract.name,
    language: "daml",
    filename: `${toPascalCase(contract.id)}.daml`,
    code: (GENERATORS[contract.id] || fallback)(spec)
  }));
}

function fallback(spec) { return header("Contract", spec); }
function toPascalCase(id) { return id.split("-").map(part => part[0].toUpperCase() + part.slice(1)).join(""); }
