// Renders Solidity SOURCE TEXT from a Financial Contract Specification. This is code
// generation only — nothing here invokes solc or deploys anything.
function header(name, spec) {
  return `// SPDX-License-Identifier: UNLICENSED\n` +
    `// Generated by Institutional Brain — Financial Specification Engine\n` +
    `// Deal: ${spec.name} (${spec.dealType})\n` +
    `pragma solidity ^0.8.24;\n\n` +
    `contract ${name} {\n`;
}

const GENERATORS = {
  "investor-registry": (spec) => header("InvestorRegistry", spec) +
`    uint256 public constant MAX_INVESTORS = ${spec.investors.count};
    uint256 public constant MAX_OWNERSHIP_BPS = ${Math.round(spec.investors.maxOwnershipPct * 100)}; // basis points
    string public eligibility = "${spec.investors.eligibility}";

    mapping(address => bool) public approved;
    mapping(address => bool) public kycPassed;

    modifier onlyApprovedInvestor(address investor) {
        require(approved[investor] && kycPassed[investor], "INVESTOR_NOT_APPROVED");
        _;
    }
}
`,
  "spv-ownership": (spec) => header(`${spec.vehicle}Ownership`, spec) +
`    uint256 public authorizedUnits = ${spec.investors.count};
    uint256 public totalIssuedUnits;
    mapping(address => uint256) public unitsOf;

    function issueUnits(address investor, uint256 units) external {
        require(totalIssuedUnits + units <= authorizedUnits, "EXCEEDS_AUTHORIZED_UNITS");
        unitsOf[investor] += units;
        totalIssuedUnits += units;
    }
}
`,
  "compliance-transfer-controller": (spec) => header("ComplianceTransferController", spec) +
`    uint256 public constant LOCKUP_MONTHS = ${spec.lockupMonths};
    bool public whitelistOnly = ${spec.compliance.whitelistOnly};
    address public approver; // "${spec.transfer.approver}"

    function canTransfer(address to, uint256 investorLockupStartMonth, uint256 currentMonth) public view returns (bool) {
        if (whitelistOnly && !isWhitelisted(to)) return false;
        if (currentMonth - investorLockupStartMonth < LOCKUP_MONTHS) return false;
        return true;
    }

    function isWhitelisted(address account) public view returns (bool) {
        // backed by InvestorRegistry.approved + kycPassed
        return approved[account];
    }

    mapping(address => bool) public approved;
}
`,
  "distribution-contract": (spec) => header("DistributionContract", spec) +
`    string public frequency = "${spec.distribution.frequency}";
    uint256 public managementFeeBps = ${Math.round(spec.finance.feePct * 100)};

    function distribute(uint256 availableCash, uint256 requestedCash) external pure returns (uint256) {
        require(requestedCash <= availableCash, "DISTRIBUTION_EXCEEDS_AVAILABLE_CASH");
        return requestedCash;
    }
}
`,
  "escrow-contract": (spec) => header("EscrowContract", spec) +
`    uint256 public reserveTarget = ${Math.round(spec.finance.reserveTargetUsd)};
    uint256 public reserveBalance;

    function fundReserve(uint256 amount) external {
        reserveBalance += amount;
    }
}
`,
  "treasury-controller": (spec) => header("TreasuryController", spec) +
`    uint256 public constant MULTISIG_THRESHOLD = ${spec.custody.multisigThreshold};
    uint256 public constant MULTISIG_SIGNERS = ${spec.custody.multisigSigners};
    mapping(bytes32 => uint256) public approvalsFor;

    function withdraw(bytes32 requestId, uint256 signatures) external pure returns (bool) {
        require(signatures >= MULTISIG_THRESHOLD, "MULTISIG_THRESHOLD_NOT_MET");
        return true;
    }
}
`,
  "debt-contract": (spec) => header("DebtContract", spec) +
`    uint256 public principalUsd = ${Math.round(spec.finance.seniorCapitalUsd)};
    uint256 public rateBps = ${Math.round(spec.finance.ratePct * 100)};
    uint256 public termYears = ${Math.round(spec.finance.termYears)};

    function accrueInterest(uint256 outstanding) external view returns (uint256) {
        return (outstanding * rateBps) / 10000 / 12;
    }
}
`,
  "waterfall-contract": (spec) => header("WaterfallContract", spec) +
`    uint256 public trancheCount = ${(spec.tranches || []).length};

    function payInPriorityOrder(uint256[] memory trancheAmounts, uint256 available) external pure returns (uint256[] memory) {
        for (uint256 i = 0; i < trancheAmounts.length; i++) {
            uint256 pay = trancheAmounts[i] < available ? trancheAmounts[i] : available;
            available -= pay;
            trancheAmounts[i] = pay;
        }
        return trancheAmounts;
    }
}
`,
  "redemption-contract": (spec) => header("RedemptionContract", spec) +
`    uint256 public constant LOCKUP_MONTHS = ${spec.lockupMonths};
    uint256 public constant NOTICE_MONTHS = ${spec.redemptionNoticeMonths || 0};

    function canRedeem(uint256 monthsHeld, uint256 noticeGivenMonths) public pure returns (bool) {
        return monthsHeld >= LOCKUP_MONTHS && noticeGivenMonths >= NOTICE_MONTHS;
    }
}
`,
  "governance-contract": (spec) => header("GovernanceContract", spec) +
`    string[] public stages = ["DealManager", "Compliance", "Legal", "Security", "InvestmentCommittee", "DeploymentAuthority"];
    mapping(bytes32 => bool) public approved;

    function approveStage(string calldata stage) external {
        approved[keccak256(bytes(stage))] = true;
    }
}
`,
  "emergency-controls": (spec) => header("EmergencyControls", spec) +
`    bool public paused;
    address public guardian; // "${spec.transfer.approver}"

    modifier whenNotPaused() {
        require(!paused, "SYSTEM_PAUSED");
        _;
    }

    function pause() external { paused = true; }
    function unpause() external { paused = false; }
}
`
};

export function generateEvmSource(spec, architecture) {
  return architecture.map(contract => ({
    id: contract.id,
    name: contract.name,
    language: "solidity",
    filename: `${toPascalCase(contract.id)}.sol`,
    code: (GENERATORS[contract.id] || fallback)(spec)
  }));
}

function fallback(spec) { return header("Contract", spec) + "}\n"; }
function toPascalCase(id) { return id.split("-").map(part => part[0].toUpperCase() + part.slice(1)).join(""); }
