// Renders Soroban (Rust) SOURCE TEXT from a Financial Contract Specification. Code generation
// only — nothing here invokes the Soroban CLI or deploys to Stellar Testnet.
function header(name, spec) {
  return `// Generated by Institutional Brain — Financial Specification Engine\n` +
    `// Deal: ${spec.name} (${spec.dealType})\n` +
    `#![no_std]\n` +
    `use soroban_sdk::{contract, contractimpl, contracttype, Address, Env, Map, Symbol};\n\n` +
    `#[contract]\npub struct ${name};\n\n`;
}

const GENERATORS = {
  "investor-registry": (spec) => header("InvestorRegistry", spec) +
`const MAX_INVESTORS: u32 = ${spec.investors.count};
const MAX_OWNERSHIP_BPS: u32 = ${Math.round(spec.investors.maxOwnershipPct * 100)};

#[contractimpl]
impl InvestorRegistry {
    pub fn approve(env: Env, investor: Address, kyc_passed: bool) {
        // eligibility: "${spec.investors.eligibility}"
        let mut approved: Map<Address, bool> = env.storage().instance().get(&"approved").unwrap_or(Map::new(&env));
        approved.set(investor, kyc_passed);
        env.storage().instance().set(&"approved", &approved);
    }
}
`,
  "spv-ownership": (spec) => header(`${spec.vehicle}Ownership`, spec) +
`const AUTHORIZED_UNITS: u32 = ${spec.investors.count};

#[contractimpl]
impl ${spec.vehicle}Ownership {
    pub fn issue_units(env: Env, investor: Address, units: u32, total_issued: u32) -> u32 {
        assert!(total_issued + units <= AUTHORIZED_UNITS, "EXCEEDS_AUTHORIZED_UNITS");
        total_issued + units
    }
}
`,
  "compliance-transfer-controller": (spec) => header("ComplianceTransferController", spec) +
`const LOCKUP_MONTHS: u32 = ${spec.lockupMonths};
const WHITELIST_ONLY: bool = ${spec.compliance.whitelistOnly};

#[contractimpl]
impl ComplianceTransferController {
    pub fn can_transfer(env: Env, to_whitelisted: bool, months_held: u32) -> bool {
        if WHITELIST_ONLY && !to_whitelisted { return false; }
        months_held >= LOCKUP_MONTHS
    }
}
`,
  "distribution-contract": (spec) => header("DistributionContract", spec) +
`// frequency: "${spec.distribution.frequency}"
const MANAGEMENT_FEE_BPS: u32 = ${Math.round(spec.finance.feePct * 100)};

#[contractimpl]
impl DistributionContract {
    pub fn distribute(env: Env, available_cash: i128, requested_cash: i128) -> i128 {
        assert!(requested_cash <= available_cash, "DISTRIBUTION_EXCEEDS_AVAILABLE_CASH");
        requested_cash
    }
}
`,
  "escrow-contract": (spec) => header("EscrowContract", spec) +
`const RESERVE_TARGET: i128 = ${Math.round(spec.finance.reserveTargetUsd)};

#[contractimpl]
impl EscrowContract {
    pub fn fund_reserve(env: Env, amount: i128, current_balance: i128) -> i128 {
        current_balance + amount
    }
}
`,
  "treasury-controller": (spec) => header("TreasuryController", spec) +
`const MULTISIG_THRESHOLD: u32 = ${spec.custody.multisigThreshold};
const MULTISIG_SIGNERS: u32 = ${spec.custody.multisigSigners};

#[contractimpl]
impl TreasuryController {
    pub fn withdraw(env: Env, signatures: u32) -> bool {
        assert!(signatures >= MULTISIG_THRESHOLD, "MULTISIG_THRESHOLD_NOT_MET");
        true
    }
}
`,
  "debt-contract": (spec) => header("DebtContract", spec) +
`const PRINCIPAL_USD: i128 = ${Math.round(spec.finance.seniorCapitalUsd)};
const RATE_BPS: u32 = ${Math.round(spec.finance.ratePct * 100)};

#[contractimpl]
impl DebtContract {
    pub fn accrue_interest(env: Env, outstanding: i128) -> i128 {
        outstanding * (RATE_BPS as i128) / 10000 / 12
    }
}
`,
  "waterfall-contract": (spec) => header("WaterfallContract", spec) +
`const TRANCHE_COUNT: u32 = ${(spec.tranches || []).length};

#[contractimpl]
impl WaterfallContract {
    pub fn pay_in_priority_order(env: Env, tranche_amount: i128, available: i128) -> i128 {
        if tranche_amount < available { tranche_amount } else { available }
    }
}
`,
  "redemption-contract": (spec) => header("RedemptionContract", spec) +
`const LOCKUP_MONTHS: u32 = ${spec.lockupMonths};
const NOTICE_MONTHS: u32 = ${spec.redemptionNoticeMonths || 0};

#[contractimpl]
impl RedemptionContract {
    pub fn can_redeem(env: Env, months_held: u32, notice_given_months: u32) -> bool {
        months_held >= LOCKUP_MONTHS && notice_given_months >= NOTICE_MONTHS
    }
}
`,
  "governance-contract": (spec) => header("GovernanceContract", spec) +
`#[contractimpl]
impl GovernanceContract {
    pub fn approve_stage(env: Env, stage: Symbol) {
        env.storage().instance().set(&stage, &true);
    }
}
`,
  "emergency-controls": (spec) => header("EmergencyControls", spec) +
`#[contracttype]
pub enum PauseState { Active, Paused }

#[contractimpl]
impl EmergencyControls {
    pub fn pause(env: Env) -> PauseState { PauseState::Paused }
    pub fn unpause(env: Env) -> PauseState { PauseState::Active }
}
`
};

export function generateStellarSource(spec, architecture) {
  return architecture.map(contract => ({
    id: contract.id,
    name: contract.name,
    language: "rust",
    filename: `${toSnakeCase(contract.id)}.rs`,
    code: (GENERATORS[contract.id] || fallback)(spec)
  }));
}

function fallback(spec) { return header("Contract", spec); }
function toSnakeCase(id) { return id.replace(/-/g, "_"); }
